modLoader="javafml"
loaderVersion="[${forge_version},)"
license="Creative Commons Attribution 4.0 International Public License"
issueTrackerURL="https://github.com/ironfprcefeild/alchemists_industry/issues"
[[mods]]
modId="alchemind"
version="${version}"
displayName="Create: Alchemist's Industry"
displayURL="https://modrinth.com/mod/create-alchemists-industry"

# JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL=""

logoFile="icon.png"
credits=""
authors="ironforcefeild"
displayTest="MATCH_VERSION"

description='''
Enhance your Create builds with the power of alchemy!
'''

[[dependencies.alchemind]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alchemind]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.alchemind]]
    modId="create"
    mandatory=true
    versionRange="[${create_version},)"
    ordering="NONE"
    side="BOTH"
